#!/bin/bash

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This script is used to generate the annotation of package info that
# records the version, revision, branch, url, user and timestamp.

# 修养unset来避免中文环境下svn命令输出的异常
unset LANG
unset LC_CTYPE
unset LC_TIME

# 记录外面传递的参数
version=$1
buildDirectory=$2

# 获取用户等基本信息
user=`whoami`
date=`date`
dir=`pwd`
cwd=`dirname $dir`

# 获取版本等信息
# 修改点1：根据实际.svn路径来修改参数，用于判断是svn还是git。
if [ -d .svn ]; then
revision=`svn info ../ | sed -n -e 's/Last Changed Rev: \(.*\)/\1/p'`
url=`svn info  ../ | sed -n -e 's/URL: \(.*\)/\1/p'`
branch=`echo $url | sed -n -e 's,.*\(branches/.*\)$,\1,p' \
                          -e 's,.*\(tags/.*\)$,\1,p' \
                          -e 's,.*trunk$,trunk,p'`
elif git rev-parse HEAD 2>/dev/null > /dev/null ; then
revision=`git log -1 --pretty=format:"%H"`
hostname=`hostname`
branch=`git branch | sed -n -e 's/^* //p'`
url="git://${hostname}${cwd}"
else
revision="Unknown"
branch="Unknown"
url="file://$cwd"
fi

# 获取所有源码校验和信息
# 修改点2：根据需要来查找某个目录下的某些文件，以对其生成校验和。此处是当前目录下的所有java源文件
if [ -n "$(which md5sum)" ]; then
  srcChecksum=`find ./ -name '*.java' | grep -v generated-sources | LC_ALL=C sort | \
      xargs md5sum | md5sum | cut -d ' ' -f 1`
else
  srcChecksum=`find ./ -name '*.java' | grep -v generated-sources | LC_ALL=C sort | \
      xargs md5 | md5 | cut -d ' ' -f 1`
fi

# 修改点2：根据实际的命名空间来创建目录
mkdir -p $buildDirectory/generated-sources/java/com/example/
# 修改点3：根据实际的命名空间来设定生成文件的目录
cat << EOF | \
  sed -e "s/VERSION/$version/" -e "s/USER/$user/" -e "s/DATE/$date/" \
      -e "s|URL|$url|" -e "s/REV/$revision/" \
      -e "s|BRANCH|$branch|" -e "s/SRCCHECKSUM/$srcChecksum/" \
      > $buildDirectory/generated-sources/java/com/example/package-info.java
/*
 * Generated by scripts/saveVersion.sh
 */
@VersionAnnotation(version="VERSION", revision="REV", branch="BRANCH",
                         user="USER", date="DATE", url="URL",
                         srcChecksum="SRCCHECKSUM")
package com.example; # 修改点4：根据实际命名空间修改
EOF